import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { invoke } from '@forge/bridge';
import './styles.css';
import { downloadCsv } from '../../shared/csv.js';

const fmtDate=(v)=>v?new Date(v).toLocaleDateString():'—';
function GroupTable({title,rows}){return <div className="card"><h2>{title}</h2><table><thead><tr><th>Name</th><th>Assets</th></tr></thead><tbody>{rows.slice(0,20).map(r=><tr key={r.name}><td>{r.name}</td><td>{r.count}</td></tr>)}</tbody></table></div>}

function App(){
 const [data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[tab,setTab]=useState('inventory'),[query,setQuery]=useState('');
 useEffect(()=>{let cancelled=false;(async()=>{try{let cursor=null,all=[],guard=0;do{const page=await invoke('getReportingInventoryPage',{cursor,limit:100});all.push(...(page?.rows||[]));cursor=page?.nextCursor||null;guard+=1;}while(cursor&&guard<500&&!cancelled);if(cancelled)return;let faultCursor=null,faultGuard=0;const faultByAsset=new Map();do{const page=await invoke('getReportingFaultPage',{cursor:faultCursor,limit:100});for(const t of (page?.rows||[])){const current=faultByAsset.get(t.assetId)||{total:0,open:0,resolved:0,lastFault:'',latestFaultKey:''};current.total+=1;if(t.resolved)current.resolved+=1;else current.open+=1;if(!current.lastFault||String(t.created||'')>current.lastFault){current.lastFault=t.created||'';current.latestFaultKey=t.key||'';}faultByAsset.set(t.assetId,current);}faultCursor=page?.nextCursor||null;faultGuard+=1;}while(faultCursor&&faultGuard<1000&&!cancelled);if(cancelled)return;const merged=all.map(r=>{const f=faultByAsset.get(r.id)||{total:0,open:0,resolved:0,lastFault:'',latestFaultKey:''};return{...r,faults:f.total,openFaults:f.open,resolvedFaults:f.resolved,lastFault:f.lastFault,latestFaultKey:f.latestFaultKey,faultDataLoaded:true};});const groupCount=(items,getter,fallback='Unspecified')=>{const map=new Map();for(const item of items){const key=String(getter(item)||'').trim()||fallback;map.set(key,(map.get(key)||0)+1);}return[...map.entries()].map(([name,count])=>({name,count})).sort((a,b)=>b.count-a.count||String(a.name).localeCompare(String(b.name)));};const unassigned=merged.filter(r=>!r.holder).length;const inRepair=merged.filter(r=>/repair/i.test(r.status)).length;const expiredWarranty=merged.filter(r=>r.warrantyState==='Expired').length;const expiringWarranty=merged.filter(r=>r.warrantyState==='Expiring soon').length;const qualityIssues=merged.filter(r=>r.qualityIssues>0).length;const openFaults=merged.reduce((s,r)=>s+Number(r.openFaults||0),0);const orgCounts=new Map();for(const row of merged)for(const org of (row.organisations||[]))orgCounts.set(org,(orgCounts.get(org)||0)+1);setData({partial:Boolean(cursor||faultCursor),summary:{totalAssets:merged.length,unassigned,inRepair,openFaults,expiredWarranty,expiringWarranty,qualityIssues},byType:groupCount(merged,r=>r.type),byStatus:groupCount(merged,r=>r.status),byLocation:groupCount(merged,r=>r.location),byHolder:groupCount(merged,r=>r.holder,'Unassigned'),byOrganisation:[...orgCounts.entries()].map(([name,count])=>({name,count})).sort((a,b)=>b.count-a.count),rows:merged,inventoryComplete:!cursor,faultsComplete:!faultCursor,faultCoverageAssets:merged.length});}catch(e){if(!cancelled)setError(e?.message||'Could not load reports.');}finally{if(!cancelled)setLoading(false);}})();return()=>{cancelled=true;};},[]);
 const rows=useMemo(()=>{const q=query.trim().toLowerCase();if(!data?.rows)return[];if(!q)return data.rows;return data.rows.filter(r=>[r.name,r.deviceId,r.type,r.manufacturer,r.model,r.serialNumber,r.holder,r.status,r.location,...r.organisations].some(v=>String(v||'').toLowerCase().includes(q)));},[data,query]);
 if(loading)return <main><div className="card">Loading Asset Manager reporting…</div></main>;
 if(error)return <main><div className="card error">{error}</div></main>;
 const s=data.summary;
 const quality=rows.filter(r=>r.qualityIssues>0);
 const faults=rows.filter(r=>r.faults!=null).sort((a,b)=>b.faults-a.faults||b.openFaults-a.openFaults);
 const assignments=[...rows].sort((a,b)=>(a.holder||'').localeCompare(b.holder||'')||a.name.localeCompare(b.name));
 const lifecycle=rows.filter(r=>r.warrantyState!=='Unknown').sort((a,b)=>String(a.warrantyExpiry).localeCompare(String(b.warrantyExpiry)));
 const inventoryExport=()=>downloadCsv(`nuvriqo-inventory-${new Date().toISOString().slice(0,10)}.csv`,['Device','Device ID','Type','Manufacturer','Model','Serial','Holder','Assignment Reference','Status','Location','Organisation','Purchase Date','Warranty Expiry','Warranty State','Primary Faults','Open Faults','Data Quality Issues'],rows.map(r=>[r.name,r.deviceId,r.type,r.manufacturer,r.model,r.serialNumber,r.holder,r.assignmentReference,r.status,r.location,r.organisations.join('; '),r.purchaseDate,r.warrantyExpiry,r.warrantyState,r.faults,r.openFaults,r.missing.join('; ')]));
 return <main>
  <header><div><span className="brand">NUVRIQO</span><h1>Asset Manager Reports</h1><p>Operational reporting across inventory, assignments, faults, organisations and data quality.</p></div><button onClick={inventoryExport}>Export current data</button></header>
  <section className="kpis"><div><small>Total assets</small><strong>{s.totalAssets}</strong></div><div><small>Open faults</small><strong>{s.openFaults}</strong></div><div><small>Unassigned</small><strong>{s.unassigned}</strong></div><div><small>In repair</small><strong>{s.inRepair}</strong></div><div><small>Warranty attention</small><strong>{s.expiredWarranty+s.expiringWarranty}</strong></div><div><small>Data quality</small><strong>{s.qualityIssues}</strong></div></section>
  <div className="tabs">{[['inventory','Inventory'],['faults','Faults'],['assignment','Assignment'],['organisation','Organisation'],['quality','Data quality'],['lifecycle','Lifecycle']].map(([k,l])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{l}</button>)}</div>
  <div className="toolbar"><input placeholder="Search reports…" value={query} onChange={e=>setQuery(e.target.value)}/><span>{rows.length} matching assets · {s.totalAssets} total</span></div>
  {tab==='inventory'&&<><section className="groups"><GroupTable title="Assets by type" rows={data.byType}/><GroupTable title="Assets by status" rows={data.byStatus}/><GroupTable title="Assets by location" rows={data.byLocation}/></section><div className="card"><h2>Inventory</h2><div className="tablewrap"><table><thead><tr><th>Device</th><th>Type</th><th>Status</th><th>Holder</th><th>Location</th><th>Serial</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><strong>{r.name}</strong><small>{r.deviceId||''}</small></td><td>{r.type}</td><td>{r.status||'—'}</td><td>{r.holder||'Unassigned'}</td><td>{r.location||'—'}</td><td>{r.serialNumber||'—'}</td></tr>)}</tbody></table></div></div></>}
  {tab==='faults'&&<div className="card"><h2>Fault history</h2><p>Devices with the highest number of primary Jira faults appear first. Fault totals are calculated from the full project-scoped ticket history stored by Asset Manager.</p><div className="tablewrap"><table><thead><tr><th>Device</th><th>Type</th><th>Primary faults</th><th>Open</th><th>Resolved</th><th>Last fault</th></tr></thead><tbody>{faults.map(r=><tr key={r.id}><td><strong>{r.name}</strong></td><td>{r.type}</td><td>{r.faults}</td><td>{r.openFaults}</td><td>{r.resolvedFaults}</td><td>{fmtDate(r.lastFault)}</td></tr>)}</tbody></table></div></div>}
  {tab==='assignment'&&<><GroupTable title="Assets by holder" rows={data.byHolder}/><div className="card"><h2>Assignment report</h2><div className="tablewrap"><table><thead><tr><th>Holder</th><th>Assignment reference</th><th>Device</th><th>Type</th><th>Status</th><th>Location</th></tr></thead><tbody>{assignments.map(r=><tr key={r.id}><td>{r.holder||'Unassigned'}</td><td>{r.assignmentReference||'—'}</td><td><strong>{r.name}</strong></td><td>{r.type}</td><td>{r.status||'—'}</td><td>{r.location||'—'}</td></tr>)}</tbody></table></div></div></>}
  {tab==='organisation'&&<><GroupTable title="Assets by organisation" rows={data.byOrganisation}/><div className="card"><h2>Organisation report</h2><p>Organisation is derived from Jira Service Management requests linked through the mapped Device ID field.</p><div className="tablewrap"><table><thead><tr><th>Organisation</th><th>Device</th><th>Type</th><th>Holder</th><th>Open faults</th></tr></thead><tbody>{rows.flatMap(r=>r.organisations.length?r.organisations.map(o=><tr key={`${r.id}-${o}`}><td>{o}</td><td><strong>{r.name}</strong></td><td>{r.type}</td><td>{r.holder||'Unassigned'}</td><td>{r.openFaults}</td></tr>):[<tr key={`${r.id}-none`}><td>Unmapped</td><td><strong>{r.name}</strong></td><td>{r.type}</td><td>{r.holder||'Unassigned'}</td><td>{r.openFaults}</td></tr>])}</tbody></table></div></div></>}
  {tab==='quality'&&<div className="card"><h2>Data quality report</h2><p>Highlights incomplete asset records that need attention.</p><div className="tablewrap"><table><thead><tr><th>Device</th><th>Missing information</th><th>Type</th><th>Holder</th><th>Location</th></tr></thead><tbody>{quality.map(r=><tr key={r.id}><td><strong>{r.name}</strong></td><td>{r.missing.join(', ')}</td><td>{r.type}</td><td>{r.holder||'Unassigned'}</td><td>{r.location||'—'}</td></tr>)}</tbody></table></div></div>}
  {tab==='lifecycle'&&<div className="card"><h2>Lifecycle & warranty</h2><div className="tablewrap"><table><thead><tr><th>Device</th><th>Purchase date</th><th>Warranty expiry</th><th>Warranty state</th><th>Status</th></tr></thead><tbody>{lifecycle.map(r=><tr key={r.id}><td><strong>{r.name}</strong></td><td>{fmtDate(r.purchaseDate)}</td><td>{fmtDate(r.warrantyExpiry)}</td><td>{r.warrantyState}</td><td>{r.status||'—'}</td></tr>)}</tbody></table></div></div>}
 </main>;
}

createRoot(document.getElementById('root')).render(<App/>);
