import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {invoke,router,view} from '@forge/bridge';
import * as XLSX from 'xlsx';
import './styles.css';

const norm=(v)=>String(v||'').trim().toLowerCase().replace(/[^a-z0-9]+/g,'');
const crewAliases={crewCode:['crewcode','crew','code','assignmentreference','staffcode','employeecode'],name:['name','crewname','displayname','fullname','employeename'],location:['location','base','station'],email:['email','emailaddress'],status:['status','employmentstatus'],notes:['notes','comment','comments']};
const usageAliases={deviceIdentifier:['deviceidentifier','deviceid','device','assetid','asset','devicename','hostname','terminalid'],deviceCode:['devicecode','imei','serial','serialnumber'],crewCode:['lastlogin','crewcode','crew','user','username','staffcode','employeecode','assignmentreference','lastuser','lastloggedinuser'],lastLoginAt:['lastsyncdatetime','lastlogindate','logindate','lastseen','lastused','lastactivity'],source:['source','system','reportsource']};
function mapWithAliases(row,aliases){const out={};for(const [k,v] of Object.entries(row||{})){const nk=norm(k);for(const [target,list] of Object.entries(aliases)){if(list.includes(nk)){out[target]=v;break;}}}return out;}
async function sheetRows(file,aliases){const data=await file.arrayBuffer();const wb=XLSX.read(data,{type:'array'});const ws=wb.Sheets[wb.SheetNames[0]];return XLSX.utils.sheet_to_json(ws,{defval:''}).map(r=>mapWithAliases(r,aliases));}
async function usageSheetRows(file){
 const data=await file.arrayBuffer();const wb=XLSX.read(data,{type:'array',cellDates:true});const ws=wb.Sheets[wb.SheetNames[0]];
 const matrix=XLSX.utils.sheet_to_json(ws,{header:1,defval:'',raw:false});
 const headerIndex=matrix.findIndex(row=>{const n=row.map(norm);return n.includes('devicename')&&n.includes('devicecode')&&n.includes('lastlogin');});
 if(headerIndex<0) throw new Error('Could not find the vPOS Device Name / Device Code / Last Login header row.');
 const headers=matrix[headerIndex].map(v=>String(v||'').trim());
 const raw=matrix.slice(headerIndex+1).filter(row=>row.some(v=>String(v||'').trim()));
 const mapped=raw.map(row=>{const obj={};headers.forEach((h,i)=>{obj[h]=row[i]??'';});return mapWithAliases(obj,usageAliases);});
 const usable=mapped.filter(r=>String(r.deviceIdentifier||'').trim()&&String(r.crewCode||'').trim()).map(r=>({...r,source:'vPOS Device Status Report'}));
 return {rows:usable,sourceRows:raw.length,skippedNoLogin:raw.length-usable.length};
}
const chunk=(items,size)=>{const out=[];for(let i=0;i<items.length;i+=size)out.push(items.slice(i,i+size));return out;};
function DeviceTypeBreakdown({groups=[]}){return groups.length?<div className="chips">{groups.map(g=><span key={g.type} className={g.count>1?'flag':''}>{g.type}: {g.count}</span>)}</div>:<span>0</span>;}

function CrewTracking(){
 const [rows,setRows]=useState([]),[report,setReport]=useState([]),[selected,setSelected]=useState(null),[message,setMessage]=useState(''),[loading,setLoading]=useState(false),[query,setQuery]=useState(''),[onlyReview,setOnlyReview]=useState(false);
 const load=async()=>{setLoading(true);try{setReport(await invoke('getCrewReport'));setMessage('');}catch(e){setMessage(e.message||'Could not load crew report.');}finally{setLoading(false);}};
 useEffect(()=>{load();},[]);
 async function readFile(file){try{const mapped=(await sheetRows(file,crewAliases)).filter(r=>Object.values(r).some(Boolean));setRows(mapped);setMessage(mapped.length?`${mapped.length} crew records ready to import.`:'No usable rows found.');}catch(e){setMessage(e.message||'Could not read file.');}}
 async function doImport(){
   if(!rows.length)return;setLoading(true);
   try{const batches=chunk(rows,100);let imported=0,failed=[];for(let i=0;i<batches.length;i+=1){setMessage(`Importing crew ${Math.min(i*100+1,rows.length)}-${Math.min((i+1)*100,rows.length)} of ${rows.length}…`);const result=await invoke('importCrew',{rows:batches[i]});imported+=result.imported||0;if(result.failed?.length)failed.push(...result.failed.map(f=>({...f,batch:i+1})));}setRows([]);await load();setMessage(`Crew import complete: ${imported} imported${failed.length?`, ${failed.length} failed`:''}.`);}catch(e){setMessage(`${e.message||'Crew import failed.'} Records already completed are kept; select the file again and rerun.`);}finally{setLoading(false);}
 }
 const filtered=useMemo(()=>report.filter(c=>{const q=query.trim().toLowerCase();const matches=!q||[c.crewCode,c.name,c.location,...(c.historicalDevices||[]),...(c.currentDeviceTypes||[]).map(g=>g.type)].some(v=>String(v||'').toLowerCase().includes(q));return matches&&(!onlyReview||c.reviewRequired);}),[report,query,onlyReview]);
 return <div className="page"><header><div><h1>Internal Crew Tracking</h1><p>Import the crew register and review current devices by device type plus Jira history by crew member.</p></div><button onClick={load} disabled={loading}>Refresh</button></header>{message&&<div className="notice">{message}</div>}
 <section className="card import"><div><h2>Crew register import</h2><p>Upload Excel or CSV. Recognised columns include Crew Code, Name, Location/Base, Email and Status. Large files are imported automatically in safe batches.</p></div><input type="file" accept=".xlsx,.xls,.csv" onChange={e=>e.target.files?.[0]&&readFile(e.target.files[0])}/>{rows.length>0&&<button className="primary" onClick={doImport} disabled={loading}>Import {rows.length} crew</button>}</section>
 <section className="kpis"><div><span>Total crew</span><strong>{report.length}</strong></div><div><span>Review required</span><strong>{report.filter(c=>c.reviewRequired).length}</strong></div><div><span>Current devices</span><strong>{report.reduce((s,c)=>s+(c.currentDeviceCount||0),0)}</strong></div><div><span>Historical tickets</span><strong>{report.reduce((s,c)=>s+(c.ticketCount||0),0)}</strong></div></section>
 <section className="card"><div className="toolbar"><input placeholder="Search crew, name, location, type or device…" value={query} onChange={e=>setQuery(e.target.value)}/><label><input type="checkbox" checked={onlyReview} onChange={e=>setOnlyReview(e.target.checked)}/> Show review required only</label></div>{loading?<div className="empty">Loading…</div>:<div className="tablewrap"><table><thead><tr><th>Crew code</th><th>Name</th><th>Location</th><th>Current devices by type</th><th>Historical devices</th><th>Tickets</th><th>Review</th></tr></thead><tbody>{filtered.map(c=><tr key={c.crewCode} onClick={()=>setSelected(c)}><td><strong>{c.crewCode}</strong></td><td>{c.name||'—'}</td><td>{c.location||'—'}</td><td><DeviceTypeBreakdown groups={c.currentDeviceTypes||[]}/></td><td>{c.historicalDeviceCount}</td><td>{c.ticketCount}</td><td>{c.reviewRequired?<span className="flag">Duplicate type</span>:'—'}</td></tr>)}</tbody></table></div>}</section>
 {selected&&<div className="modal" onClick={()=>setSelected(null)}><div className="dialog" onClick={e=>e.stopPropagation()}><div className="dialoghead"><div><h2>{selected.crewCode}{selected.name?` · ${selected.name}`:''}</h2><p>{selected.location||'No location'} · {selected.status||'—'}</p></div><button onClick={()=>setSelected(null)}>×</button></div>{selected.reviewRequired&&<div className="warning">Review required because this crew member has more than one current device in the same type: {(selected.duplicateDeviceTypes||[]).map(g=>`${g.type} (${g.count})`).join(', ')}.</div>}<h3>Current devices by type</h3>{selected.currentDeviceTypes?.length?selected.currentDeviceTypes.map(group=><div key={group.type} className="device-type-group"><h4>{group.type} <span>({group.count})</span></h4><ul>{group.devices.map(d=><li key={d.id}><strong>{d.identifier}</strong> · {d.status||'—'} · {d.location||'—'}</li>)}</ul></div>):<p>No devices currently assigned.</p>}<h3>Historical devices</h3><div className="chips">{(selected.historicalDevices||[]).map(d=><span key={d}>{d}</span>)}</div><h3>Jira ticket history</h3>{selected.tickets?.length?<div className="tablewrap"><table><thead><tr><th>Issue</th><th>Created</th><th>Status</th><th>Devices</th><th>Summary</th></tr></thead><tbody>{selected.tickets.map(t=><tr key={t.key}><td><button className="link" onClick={()=>router.open(`/browse/${t.key}`)}>{t.key}</button></td><td>{t.created?new Date(t.created).toLocaleDateString():'—'}</td><td>{t.status||'—'}</td><td>{t.devices.join(', ')||'—'}</td><td>{t.summary||'—'}</td></tr>)}</tbody></table></div>:<p>No matching Jira tickets.</p>}</div></div>}
 </div>;
}

const stateLabel={match:'Match','assigned-automatically':'Assigned automatically','assignment-mismatch':'Assignment mismatch','crew-not-in-register':'Crew not in register','device-not-in-assets':'Device not in Asset Manager','crew-and-device-missing':'Crew and device not found'};
function DeviceUsage(){
 const [rows,setRows]=useState([]),[fileMeta,setFileMeta]=useState(null),[report,setReport]=useState({rows:[]}),[message,setMessage]=useState(''),[loading,setLoading]=useState(false),[query,setQuery]=useState(''),[onlyReview,setOnlyReview]=useState(true),[offset,setOffset]=useState(0);
 const load=async(nextOffset=0)=>{setLoading(true);try{const data=await invoke('getUsageReconciliation',{offset:nextOffset,limit:250,query,reviewOnly:onlyReview});setReport(data);setOffset(nextOffset);}catch(e){setMessage(e.message||'Could not load reconciliation report.');}finally{setLoading(false);}};
 useEffect(()=>{load(0);},[]);
 useEffect(()=>{const timer=setTimeout(()=>load(0),350);return()=>clearTimeout(timer);},[query,onlyReview]);
 async function readFile(file){
   try{setLoading(true);setMessage('Reading vPOS report…');const parsed=await usageSheetRows(file);setRows(parsed.rows);setFileMeta({name:file.name,sourceRows:parsed.sourceRows,skippedNoLogin:parsed.skippedNoLogin});setMessage(`${parsed.rows.length} devices with a Last Login are ready to reconcile from ${parsed.sourceRows} report rows. ${parsed.skippedNoLogin} rows without a usable Last Login will be skipped.`);}catch(e){setRows([]);setFileMeta(null);setMessage(e.message||'Could not read the vPOS device report.');}finally{setLoading(false);}
 }
 async function doImport(){
   if(!rows.length||!fileMeta)return;setLoading(true);
   const sessionId=`${Date.now()}-${Math.random().toString(36).slice(2,10)}`;
   try{
     await invoke('beginDeviceUsageImport',{sessionId,sourceFile:fileMeta.name,sourceRows:fileMeta.sourceRows,usableRows:rows.length,skippedNoLogin:fileMeta.skippedNoLogin});
     const batches=chunk(rows,100);let imported=0,assigned=0,mismatches=0;
     for(let i=0;i<batches.length;i+=1){setMessage(`Reconciling devices ${i*100+1}-${Math.min((i+1)*100,rows.length)} of ${rows.length}… ${assigned} automatically assigned, ${mismatches} mismatches so far.`);const result=await invoke('importDeviceUsageBatch',{sessionId,batchIndex:i,rows:batches[i],finalBatch:i===batches.length-1});imported+=result.imported||0;assigned+=result.assignedCount||0;mismatches+=result.mismatchCount||0;}
     setRows([]);setFileMeta(null);await load(0);setMessage(`Reconciliation complete: ${imported} devices checked, ${assigned} previously unassigned assets assigned automatically, ${mismatches} assignment mismatches highlighted.`);
   }catch(e){setMessage(`${e.message||'Device reconciliation failed.'} Completed batches are retained in the current import session.`);}finally{setLoading(false);}
 }
 const canPrev=offset>0,canNext=offset+(report.rows?.length||0)<(report.filteredCount||0);
 return <div className="page"><header><div><h1>Device Usage Reconciliation</h1><p>Import the native vPOS Device Status report and compare Last Login against Asset Manager's current assignment.</p></div><button onClick={()=>load(offset)} disabled={loading}>Refresh</button></header>{message&&<div className="notice">{message}</div>}
 <section className="card import"><div><h2>Import vPOS device status report</h2><p>The importer automatically finds the Device Name / Device Code / Last Login header row, even when the report contains title and filter rows first. Unassigned assets are assigned only when the Last Login crew exists in the imported crew register; existing assignments are never overwritten.</p></div><input type="file" accept=".xlsx,.xls,.csv" onChange={e=>e.target.files?.[0]&&readFile(e.target.files[0])}/>{rows.length>0&&<button className="primary" onClick={doImport} disabled={loading}>Reconcile {rows.length} devices</button>}</section>
 <section className="kpis usage-kpis"><div><span>Devices checked</span><strong>{report.importedCount||0}</strong></div><div><span>Assigned automatically</span><strong>{report.assignedCount||0}</strong></div><div><span>Assignment mismatches</span><strong>{report.mismatchCount||0}</strong></div><div><span>Clean matches</span><strong>{report.matchedCount||0}</strong></div><div><span>Crew not in register</span><strong>{report.notInCrewListCount||0}</strong></div><div><span>Devices not found</span><strong>{report.missingAssetCount||0}</strong></div></section>
 <section className="card"><div className="toolbar"><input placeholder="Search device, code, crew, type or location…" value={query} onChange={e=>setQuery(e.target.value)}/><label><input type="checkbox" checked={onlyReview} onChange={e=>setOnlyReview(e.target.checked)}/> Show exceptions only</label></div>{report.importedAt&&<p className="snapshot">Snapshot: {report.sourceFile||'Device report'} · {report.sourceRows||0} source rows · {report.skippedNoLogin||0} without Last Login skipped · processed {new Date(report.importedAt).toLocaleString()}</p>}{loading?<div className="empty">Working…</div>:<div className="tablewrap"><table><thead><tr><th>Device</th><th>Type</th><th>Device code</th><th>Last logged-in crew</th><th>Crew name</th><th>Asset Manager assignment</th><th>Last sync</th><th>Result</th><th>Action</th></tr></thead><tbody>{(report.rows||[]).map(r=><tr key={`${r.deviceIdentifier}-${r.deviceCode}-${r.crewCode}`}><td><strong>{r.deviceIdentifier}</strong>{r.assetName&&r.assetName!==r.deviceIdentifier?<small className="subline">{r.assetName}</small>:null}</td><td>{r.assetType||'—'}</td><td>{r.deviceCode||'—'}</td><td>{r.crewCode||'—'}</td><td>{r.crewName||'—'}</td><td>{r.assignedCrewCode||'Unassigned'}</td><td>{r.lastLoginAt||'—'}</td><td><span className={`state ${r.reviewRequired?'bad':'good'}`}>{stateLabel[r.state]||r.state}</span></td><td>{r.action||'—'}</td></tr>)}</tbody></table></div>}<div className="toolbar"><span>{report.filteredCount||0} matching rows{report.filteredCount?` · showing ${Math.min(offset+1,report.filteredCount)}-${Math.min(offset+(report.rows?.length||0),report.filteredCount)}`:''}</span><div><button disabled={!canPrev||loading} onClick={()=>load(Math.max(0,offset-250))}>Previous</button> <button disabled={!canNext||loading} onClick={()=>load(offset+250)}>Next</button></div></div></section>
 <section className="card help"><h2>Reconciliation rules</h2><p><strong>Unassigned + known crew:</strong> Asset Manager assigns the device to that crew member and writes an audit-history event. <strong>Already assigned to the same crew:</strong> Match. <strong>Already assigned to somebody else:</strong> Assignment mismatch is highlighted and the existing assignment is left untouched. Unknown crew codes and devices not found in Asset Manager are also highlighted for review.</p></section></div>;
}

function App(){
 const [route,setRoute]=useState('crew-tracking');
 useEffect(()=>{let unlisten;view.createHistory().then(history=>{const apply=location=>{const p=(location?.pathname||'').replace(/^\/+|\/+$/g,'');setRoute(p==='device-usage'?'device-usage':'crew-tracking');};apply(history.location);unlisten=history.listen(apply);}).catch(()=>{});return()=>unlisten?.();},[]);
 return route==='device-usage'?<DeviceUsage/>:<CrewTracking/>;
}
createRoot(document.getElementById('root')).render(<App/>);
