import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { invoke, view } from '@forge/bridge';
import './styles.css';

function DeviceField() {
  const [current,setCurrent]=useState(null); const [query,setQuery]=useState(''); const [devices,setDevices]=useState([]); const [issueKey,setIssueKey]=useState(''); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [applyLocation,setApplyLocation]=useState(false); const [applyOwner,setApplyOwner]=useState(false); const [message,setMessage]=useState(''); const [error,setError]=useState('');
  useEffect(()=>{view.getContext().then((context)=>{const value=context?.extension?.fieldValue||null;setCurrent(value);setQuery(value?.name||'');setIssueKey(context?.extension?.issue?.key||'');}).catch(()=>setError('Could not load the current Device value.')).finally(()=>setLoading(false));},[]);
  useEffect(()=>{if(loading)return undefined;const timer=setTimeout(async()=>{try{setError('');const results=await invoke('searchDevices',{query});setDevices(Array.isArray(results)?results:[]);}catch(e){setDevices([]);setError(e?.message||'Could not load devices.');}},200);return()=>clearTimeout(timer);},[query,loading]);
  async function choose(device){setSaving(true);setError('');setMessage('Selecting device…');try{await view.submit({id:device.id,name:device.identifier||device.name});setCurrent(device);setQuery(device.identifier||device.name);if(issueKey){setMessage('Updating ticket from Asset Manager…');const result=await invoke('applyAssetToIssue',{assetId:device.id,issueKey,choices:{deviceType:true,location:applyLocation,owner:applyOwner}});setMessage(result?.updated?.length?`Selected ${device.identifier||device.name}. Updated: ${result.updated.join(', ')}`:`Selected ${device.identifier||device.name}.`);}else setMessage(`Selected ${device.identifier||device.name}. Mapped metadata will be available when the ticket is created.`);}catch(e){setError(e?.message||'Could not select this asset.');setMessage('');}finally{setSaving(false);}}
  async function clearValue(){setSaving(true);setError('');setMessage('');try{await view.submit(null);setCurrent(null);setQuery('');}catch(e){setError(e?.message||'Could not clear Device.');}finally{setSaving(false);}}
  if(loading)return <div className="field-shell"><span className="muted">Loading Asset Manager devices…</span></div>;
  return <div className="field-shell">
    <div className="picker-title"><strong>Select an Asset Manager device</strong><small>Search by device identifier, name, type, model, serial number, holder or location.</small></div>
    <div className="picker-wrap"><input autoFocus value={query} onChange={(e)=>{setQuery(e.target.value);setMessage('');}} placeholder="Search device identifier, model, holder…" aria-label="Search Asset Manager devices" disabled={saving}/>{query&&!saving&&<button className="clear" type="button" onClick={clearValue} aria-label="Clear Device">×</button>}</div>
    <div className="results" role="listbox" aria-label="Asset Manager devices">{devices.map((device)=><button type="button" role="option" aria-selected={current?.id===device.id} key={device.id} className={current?.id===device.id?'selected':''} onClick={()=>choose(device)} disabled={saving}><div className="result-head"><strong>{device.identifier||device.name}</strong>{device.status&&<span>{device.status}</span>}</div><small>{[device.type,[device.manufacturer,device.model].filter(Boolean).join(' '),device.location].filter(Boolean).join(' · ')}</small>{device.holder&&<small>Holder: {device.holder}</small>}</button>)}{!devices.length&&!error&&<div className="empty">No matching Asset Manager devices. A new device can still be recorded using the mapped Jira device identifier field.</div>}</div>
    <div className="sync-options"><strong>Ticket autofill</strong><span>Choosing an asset writes its identifier to the mapped Jira device identifier field and fills Device Type automatically.</span><label><input type="checkbox" checked={applyLocation} onChange={(e)=>setApplyLocation(e.target.checked)} disabled={saving}/> Also apply location</label><label><input type="checkbox" checked={applyOwner} onChange={(e)=>setApplyOwner(e.target.checked)} disabled={saving}/> Also apply holder / assignment reference</label><small>Location and holder remain opt-in because those details may intentionally differ on an individual ticket.</small></div>
    {message&&<div className="success">{message}</div>}{error&&<div className="error">{error}</div>}
  </div>;
}
createRoot(document.getElementById('root')).render(<DeviceField/>);
