import React, { useEffect, useMemo, useState } from 'react';
import { invoke } from './invoke.js';
import { downloadCsv } from '../../shared/csv.js';
import { loadFullReport } from './reportData';

const fmtDate=(v)=>v?new Date(v).toLocaleDateString():'—';
function groupCount(items,getter,fallback='Unspecified'){const map=new Map();for(const item of items){const key=String(getter(item)||'').trim()||fallback;map.set(key,(map.get(key)||0)+1);}return [...map.entries()].map(([name,count])=>({name,count})).sort((a,b)=>b.count-a.count||a.name.localeCompare(b.name));}
async function loadReportingData(onProgress){
 const{assets,reports,partial}=await loadFullReport(onProgress);
 const reportMap=new Map((reports||[]).map(r=>[r.assetId,r]));
 const today=new Date(),in90=new Date(today.getTime()+90*86400000);
 const rows=(assets||[]).map(a=>{const f=reportMap.get(a.id)||{};const expiry=a.warrantyExpiry?new Date(a.warrantyExpiry):null;const warrantyState=!expiry||Number.isNaN(expiry.getTime())?'Unknown':expiry<today?'Expired':expiry<=in90?'Expiring soon':'In warranty';const missing=[];if(!a.serialNumber)missing.push('Serial number');if(!a.type||String(a.type).toLowerCase()==='other')missing.push('Device type');if(!a.location)missing.push('Location');if(!a.assigneeName&&!a.crewCode)missing.push('Holder');return{id:a.id,name:a.name,deviceId:a.jiraIdentifier||'',type:a.type||'Other',manufacturer:a.manufacturer||'',model:a.model||'',serialNumber:a.serialNumber||'',holder:a.assigneeName||a.crewCode||'',assignmentReference:a.crewCode||'',status:a.status||'',location:a.location||'',purchaseDate:a.purchaseDate||'',warrantyExpiry:a.warrantyExpiry||'',warrantyState,organisations:[],faults:f.total||0,openFaults:f.open||0,resolvedFaults:f.resolved||0,lastFault:f.lastFault||'',latestFaultDescription:f.latestFault?.fault||f.latestFault?.summary||'',latestFaultKey:f.latestFault?.key||'',missing,qualityIssues:missing.length};});
 return{partial,summary:{totalAssets:rows.length,openFaults:rows.reduce((s,r)=>s+r.openFaults,0),unassigned:rows.filter(r=>!r.holder).length,inRepair:rows.filter(r=>/repair/i.test(r.status)).length,expiredWarranty:rows.filter(r=>r.warrantyState==='Expired').length,expiringWarranty:rows.filter(r=>r.warrantyState==='Expiring soon').length,qualityIssues:rows.filter(r=>r.qualityIssues>0).length},byType:groupCount(rows,r=>r.type),byStatus:groupCount(rows,r=>r.status),byLocation:groupCount(rows,r=>r.location),byHolder:groupCount(rows,r=>r.holder,'Unassigned'),byOrganisation:[],rows};
}
function GroupTable({title,rows=[]}){return <div className="card"><h2>{title}</h2><div className="table-wrap"><table><thead><tr><th>Name</th><th>Assets</th></tr></thead><tbody>{rows.length?rows.slice(0,20).map(r=><tr key={r.name}><td>{r.name}</td><td>{r.count}</td></tr>):<tr><td colSpan="2">No data available yet</td></tr>}</tbody></table></div></div>}
export default function ReportsWorkspace({onBack}){
 const [data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[tab,setTab]=useState('inventory'),[query,setQuery]=useState(''),[progress,setProgress]=useState('');
 useEffect(()=>{loadReportingData(setProgress).then(setData).catch(e=>setError(e?.message||'Could not load reports.')).finally(()=>setLoading(false));},[]);
 const rows=useMemo(()=>{const q=query.trim().toLowerCase();if(!data?.rows)return[];if(!q)return data.rows;return data.rows.filter(r=>[r.name,r.deviceId,r.type,r.manufacturer,r.model,r.serialNumber,r.holder,r.status,r.location,r.latestFaultDescription,r.latestFaultKey].some(v=>String(v||'').toLowerCase().includes(q)));},[data,query]);
 if(loading)return <main><div className="card">{progress||'Loading Asset Manager reports…'}</div></main>;
 if(error)return <main><div className="card report-warning">{error}</div></main>;
 const s=data.summary||{};const quality=rows.filter(r=>r.qualityIssues>0);const faults=[...rows].sort((a,b)=>b.faults-a.faults||b.openFaults-a.openFaults);const assignments=[...rows].sort((a,b)=>(a.holder||'').localeCompare(b.holder||'')||a.name.localeCompare(b.name));const lifecycle=rows.filter(r=>r.warrantyState!=='Unknown').sort((a,b)=>String(a.warrantyExpiry).localeCompare(String(b.warrantyExpiry)));
 const exportData=()=>downloadCsv(`nuvriqo-asset-report-${new Date().toISOString().slice(0,10)}.csv`,['Device','Device ID','Type','Manufacturer','Model','Serial','Holder','Assignment Reference','Status','Location','Latest Device Fault','Latest Fault Ticket','Purchase Date','Warranty Expiry','Warranty State','Primary Faults','Open Faults','Data Quality Issues'],rows.map(r=>[r.name,r.deviceId,r.type,r.manufacturer,r.model,r.serialNumber,r.holder,r.assignmentReference,r.status,r.location,r.latestFaultDescription,r.latestFaultKey,r.purchaseDate,r.warrantyExpiry,r.warrantyState,r.faults,r.openFaults,(r.missing||[]).join('; ')]));
 return <main className="reports-workspace"><div className="toolbar"><button className="secondary" onClick={onBack}>← Overview</button><button className="primary" onClick={exportData}>Export report CSV</button></div>{data.partial&&<div className="card report-warning">Some Jira tickets or assets could not be loaded, so these figures may be incomplete. Refresh to try again.</div>}<div className="page-title"><span className="brand">NUVRIQO</span><h1>Asset Manager Reports</h1><p>Operational reporting across inventory, assignments, faults, lifecycle and data quality.</p></div>
 <div className="report-stats"><div><strong>{s.totalAssets||0}</strong><span>Total assets</span></div><div><strong>{s.openFaults||0}</strong><span>Open faults</span></div><div><strong>{s.unassigned||0}</strong><span>Unassigned</span></div><div><strong>{s.inRepair||0}</strong><span>In repair</span></div><div><strong>{(s.expiredWarranty||0)+(s.expiringWarranty||0)}</strong><span>Warranty attention</span></div><div><strong>{s.qualityIssues||0}</strong><span>Data quality</span></div></div>
 <div className="filters">{[['inventory','Inventory'],['faults','Faults'],['assignment','Assignment'],['quality','Data quality'],['lifecycle','Lifecycle']].map(([k,l])=><button key={k} className={tab===k?'primary':'secondary'} onClick={()=>setTab(k)}>{l}</button>)}<input className="search" placeholder="Search report data…" value={query} onChange={e=>setQuery(e.target.value)}/></div>
 {tab==='inventory'&&<><div className="detail-grid"><GroupTable title="Assets by type" rows={data.byType}/><GroupTable title="Assets by status" rows={data.byStatus}/><GroupTable title="Assets by location" rows={data.byLocation}/></div><ReportTable title="Inventory" headers={['Device','Type','Status','Holder','Location','Serial']} rows={rows.map(r=>[r.name,r.type,r.status||'—',r.holder||'Unassigned',r.location||'—',r.serialNumber||'—'])}/></>}
 {tab==='faults'&&<ReportTable title="Fault history" subtitle="Uses the mapped Jira Device Fault field when available; otherwise falls back to the Jira summary." headers={['Device','Type','Device fault','Primary faults','Open','Resolved','Last fault']} rows={faults.map(r=>[r.name,r.type,r.latestFaultDescription||'—',r.faults,r.openFaults,r.resolvedFaults,fmtDate(r.lastFault)])}/>} 
 {tab==='assignment'&&<><GroupTable title="Assets by holder" rows={data.byHolder}/><ReportTable title="Assignment report" headers={['Holder','Assignment reference','Device','Type','Status','Location']} rows={assignments.map(r=>[r.holder||'Unassigned',r.assignmentReference||'—',r.name,r.type,r.status||'—',r.location||'—'])}/></>}
 {tab==='quality'&&<ReportTable title="Data quality report" subtitle="Incomplete asset records that need attention." headers={['Device','Missing information','Type','Holder','Location']} rows={quality.map(r=>[r.name,(r.missing||[]).join(', '),r.type,r.holder||'Unassigned',r.location||'—'])}/>} 
 {tab==='lifecycle'&&<ReportTable title="Lifecycle & warranty" headers={['Device','Purchase date','Warranty expiry','Warranty state','Status']} rows={lifecycle.map(r=>[r.name,fmtDate(r.purchaseDate),fmtDate(r.warrantyExpiry),r.warrantyState,r.status||'—'])}/>} 
 </main>;
}
function ReportTable({title,subtitle,headers,rows}){return <div className="card fault-card"><div className="section-head"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div><span>{rows.length} rows</span></div><div className="table-wrap"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{j===0?<strong>{v}</strong>:v}</td>)}</tr>):<tr><td colSpan={headers.length}>No matching report data</td></tr>}</tbody></table></div></div>}
