import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { invoke, requestJira } from '@forge/bridge';
import './styles.css';
import './reports.css';

const normalise=(v)=>String(v??'').trim().toLowerCase().replace(/\s+/g,' ');
const formatDate=(v)=>v?new Date(v).toLocaleDateString():'—';
const fieldValues=(value)=>{if(value==null)return[];if(Array.isArray(value))return value.flatMap(fieldValues);if(typeof value==='string'||typeof value==='number')return[String(value).trim()].filter(Boolean);if(typeof value==='object'){const candidate=value.value??value.name??value.label??value.displayName??value.objectKey??value.key;return candidate?[String(candidate).trim()]:[];}return[];};
function csvEscape(value){const text=String(value??'');return /[",\n]/.test(text)?`"${text.replaceAll('"','""')}"`:text;}
function downloadCsv(filename,headers,rows){const csv=[headers,...rows].map(r=>r.map(csvEscape).join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=filename;a.click();URL.revokeObjectURL(url);}
function countBy(rows,getter,blank='Unspecified'){const map=new Map();for(const row of rows){const value=String(getter(row)||'').trim()||blank;map.set(value,(map.get(value)||0)+1);}return [...map.entries()].map(([name,count])=>({name,count})).sort((a,b)=>b.count-a.count||a.name.localeCompare(b.name));}
function warrantyState(asset){if(!asset.warrantyExpiry)return'No warranty date';const expiry=new Date(asset.warrantyExpiry);if(Number.isNaN(expiry.getTime()))return'Invalid warranty date';const days=Math.ceil((expiry-Date.now())/86400000);if(days<0)return'Expired';if(days<=90)return'Expiring within 90 days';return'Current';}
function qualityFlags(asset){const flags=[];if(!asset.serialNumber)flags.push('Missing serial number');if(!asset.type||normalise(asset.type)==='other')flags.push('Missing/specific device type');if(!asset.location)flags.push('Missing location');if(!asset.assigneeName&&!asset.crewCode)flags.push('Unassigned');if(!asset.jiraIdentifier)flags.push('No Jira Device ID');return flags;}
function findOrganizationsField(fields){return (fields||[]).find(f=>{const name=normalise(f?.name),custom=normalise(f?.schema?.custom);return name==='organizations'||name==='organisations'||custom.includes('organization');})||null;}
async function loadOrganisationMap(settings){const result=new Map();if(!settings?.jiraAssetField?.id)return result;try{const fieldsResponse=await requestJira('/rest/api/3/field');if(!fieldsResponse.ok)return result;const fields=await fieldsResponse.json();const organisationField=findOrganizationsField(fields);if(!organisationField)return result;const numericId=String(settings.jiraAssetField.id).replace('customfield_','');let token;for(let guard=0;guard<250;guard+=1){const body={jql:`cf[${numericId}] is not EMPTY ORDER BY created DESC`,fields:[settings.jiraAssetField.id,organisationField.id],maxResults:100};if(token)body.nextPageToken=token;const response=await requestJira('/rest/api/3/search/jql',{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json'},body:JSON.stringify(body)});if(!response.ok)break;const data=await response.json();for(const issue of data.issues||[]){const orgs=fieldValues(issue.fields?.[organisationField.id]);for(const identifier of fieldValues(issue.fields?.[settings.jiraAssetField.id])){const key=normalise(identifier);if(!result.has(key))result.set(key,new Set());for(const org of orgs)if(org)result.get(key).add(org);}}token=data.nextPageToken||null;if(!token)break;}}catch{}return result;}
function Bars({title,rows}){const max=Math.max(...rows.map(r=>r.count),1);return <div className="card report-chart"><h2>{title}</h2><div className="report-bars">{rows.slice(0,10).map(r=><div key={r.name}><span>{r.name}</span><div><i style={{width:`${Math.max(4,Math.round(r.count/max*100))}%`}}/></div><b>{r.count}</b></div>)}</div></div>;}

function ReportsApp(){
  const [assets,setAssets]=useState([]),[faults,setFaults]=useState([]),[settings,setSettings]=useState(null),[orgMap,setOrgMap]=useState(new Map()),[loading,setLoading]=useState(true),[error,setError]=useState(''),[tab,setTab]=useState('inventory'),[query,setQuery]=useState('');
  useEffect(()=>{(async()=>{try{const [assetRows,faultRows,cfg]=await Promise.all([invoke('listAssets',{}),invoke('getAssetReport'),invoke('getSettings')]);setAssets(assetRows||[]);setFaults(faultRows||[]);setSettings(cfg||{});setOrgMap(await loadOrganisationMap(cfg||{}));}catch(e){setError(e?.message||'Could not load reports.');}finally{setLoading(false);}})();},[]);
  const faultById=useMemo(()=>new Map(faults.map(r=>[r.assetId,r])),[faults]);
  const rows=useMemo(()=>assets.map(a=>{const f=faultById.get(a.id)||{};const organisations=[...(orgMap.get(normalise(a.jiraIdentifier||a.name))||new Set())].sort();return{id:a.id,name:a.name||'',deviceId:a.jiraIdentifier||a.name||'',type:a.type||'',manufacturer:a.manufacturer||'',model:a.model||'',serialNumber:a.serialNumber||'',holder:a.assigneeName||a.crewCode||'',assignmentReference:a.crewCode||'',status:a.status||'',location:a.location||'',purchaseDate:a.purchaseDate||'',warrantyExpiry:a.warrantyExpiry||'',warrantyState:warrantyState(a),organisations,primaryFaults:f.total||0,openFaults:f.open||0,resolvedFaults:f.resolved||0,latestFaultDate:f.lastFault||'',latestFaultKey:f.latestFault?.key||'',qualityFlags:qualityFlags(a)};}),[assets,faultById,orgMap]);
  const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return q?rows.filter(r=>[r.name,r.deviceId,r.type,r.manufacturer,r.model,r.serialNumber,r.holder,r.assignmentReference,r.status,r.location,...r.organisations,...r.qualityFlags].some(v=>String(v||'').toLowerCase().includes(q))):rows;},[rows,query]);
  if(loading)return <main className="report-main"><div className="card">Loading Asset Manager reporting…</div></main>;
  if(error)return <main className="report-main"><div className="card report-error">{error}</div></main>;
  const summary={total:rows.length,inUse:rows.filter(r=>['in use','assigned','active'].includes(normalise(r.status))).length,available:rows.filter(r=>normalise(r.status)==='available').length,repair:rows.filter(r=>['repair','in repair'].includes(normalise(r.status))).length,openFaults:rows.reduce((s,r)=>s+r.openFaults,0),unassigned:rows.filter(r=>!r.holder).length,warranty:rows.filter(r=>r.warrantyState==='Expiring within 90 days').length,quality:rows.filter(r=>r.qualityFlags.length).length};
  const organisations=[];const om=new Map();for(const r of rows)for(const name of r.organisations){if(!om.has(name))om.set(name,{name,assets:0,faults:0,open:0});const o=om.get(name);o.assets+=1;o.faults+=r.primaryFaults;o.open+=r.openFaults;}organisations.push(...[...om.values()].sort((a,b)=>b.assets-a.assets||a.name.localeCompare(b.name)));
  const display=tab==='faults'?[...filtered].sort((a,b)=>b.primaryFaults-a.primaryFaults||b.openFaults-a.openFaults):tab==='quality'?filtered.filter(r=>r.qualityFlags.length):tab==='assignments'?[...filtered].sort((a,b)=>String(a.holder||'').localeCompare(String(b.holder||''))):filtered;
  const exportRows=filtered.map(r=>[r.deviceId,r.name,r.type,r.manufacturer,r.model,r.serialNumber,r.holder,r.assignmentReference,r.status,r.location,r.organisations.join('; '),r.primaryFaults,r.openFaults,r.resolvedFaults,r.latestFaultKey,r.latestFaultDate,r.purchaseDate,r.warrantyExpiry,r.warrantyState,r.qualityFlags.join('; ')]);
  return <main className="report-main"><header className="report-header"><div><span className="brand">NUVRIQO</span><h1>Asset Reports</h1><p>Inventory, support faults, assignments, organisations and data quality in one place.</p></div><button className="primary" onClick={()=>downloadCsv(`nuvriqo-asset-report-${new Date().toISOString().slice(0,10)}.csv`,['Device ID','Device name','Type','Manufacturer','Model','Serial number','Holder','Assignment reference','Status','Location','Organisations','Primary faults','Open faults','Resolved faults','Latest fault','Latest fault date','Purchase date','Warranty expiry','Warranty state','Data quality issues'],exportRows)}>Export CSV</button></header>
  <section className="report-kpis">{[['Total assets',summary.total],['In use',summary.inUse],['Available',summary.available],['In repair',summary.repair],['Open faults',summary.openFaults],['Unassigned',summary.unassigned],['Warranty ≤90 days',summary.warranty],['Data quality issues',summary.quality]].map(([label,value])=><div className="card" key={label}><small>{label}</small><strong>{value}</strong></div>)}</section>
  <section className="report-charts"><Bars title="Assets by type" rows={countBy(rows,r=>r.type)}/><Bars title="Assets by status" rows={countBy(rows,r=>r.status)}/><Bars title="Assets by location" rows={countBy(rows,r=>r.location)}/></section>
  <div className="report-toolbar"><div className="report-tabs">{[['inventory','Inventory'],['faults','Faults'],['assignments','Assignments'],['organisations','Organisations'],['quality','Data quality']].map(([key,label])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}>{label}</button>)}</div><input placeholder="Search reports…" value={query} onChange={e=>setQuery(e.target.value)}/></div>
  {tab==='organisations'?<div className="card report-table"><h2>Organisation summary</h2><div className="table-wrap"><table><thead><tr><th>Organisation</th><th>Assets</th><th>Primary faults</th><th>Open faults</th></tr></thead><tbody>{organisations.map(o=><tr key={o.name}><td><strong>{o.name}</strong></td><td>{o.assets}</td><td>{o.faults}</td><td>{o.open}</td></tr>)}</tbody></table>{!organisations.length&&<div className="empty-small">No organisation-linked assets found.</div>}</div></div>:<div className="card report-table"><div className="table-wrap"><table><thead><tr><th>Device</th><th>Type</th><th>Holder</th><th>Status</th><th>Location</th><th>Organisation</th>{tab==='faults'&&<><th>Faults</th><th>Open</th><th>Latest</th></>}{tab==='quality'&&<th>Issues</th>}{tab==='inventory'&&<><th>Serial</th><th>Warranty</th></>}</tr></thead><tbody>{display.map(r=><tr key={r.id}><td><strong>{r.name||r.deviceId}</strong><small>{r.deviceId!==r.name?r.deviceId:''}</small></td><td>{r.type||'—'}</td><td>{r.holder||'Unassigned'}</td><td>{r.status||'—'}</td><td>{r.location||'—'}</td><td>{r.organisations.join(', ')||'—'}</td>{tab==='faults'&&<><td>{r.primaryFaults}</td><td>{r.openFaults}</td><td>{r.latestFaultKey?<><strong>{r.latestFaultKey}</strong><small>{formatDate(r.latestFaultDate)}</small></>:'—'}</td></>}{tab==='quality'&&<td>{r.qualityFlags.join(', ')}</td>}{tab==='inventory'&&<><td>{r.serialNumber||'—'}</td><td>{r.warrantyState}{r.warrantyExpiry?<small>{formatDate(r.warrantyExpiry)}</small>:null}</td></>}</tr>)}</tbody></table></div></div>}
  <div className="report-footer">{settings?.jiraAssetField?.name?`Device source: ${settings.jiraAssetField.name}`:'Jira Device ID field is not mapped.'}</div></main>;
}

createRoot(document.getElementById('root')).render(<ReportsApp/>);
