import React, { useEffect, useMemo, useState } from 'react';
import { invoke } from '@forge/bridge';

const fmtDate=(v)=>v?new Date(v).toLocaleDateString():'—';
const esc=(v)=>{const s=String(v??'');return /[",\n]/.test(s)?`"${s.replaceAll('"','""')}"`:s;};
function downloadCsv(name,headers,rows){const csv=[headers,...rows].map(r=>r.map(esc).join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);}
function GroupTable({title,rows=[]}){return <div className="card"><h2>{title}</h2><div className="table-wrap"><table><thead><tr><th>Name</th><th>Assets</th></tr></thead><tbody>{rows.slice(0,20).map(r=><tr key={r.name}><td>{r.name}</td><td>{r.count}</td></tr>)}</tbody></table></div></div>}
export default function ReportsWorkspace({onBack}){
 const [data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[tab,setTab]=useState('inventory'),[query,setQuery]=useState('');
 useEffect(()=>{invoke('getReportingData').then(setData).catch(e=>setError(e?.message||'Could not load reports.')).finally(()=>setLoading(false));},[]);
 const rows=useMemo(()=>{const q=query.trim().toLowerCase();if(!data?.rows)return[];if(!q)return data.rows;return data.rows.filter(r=>[r.name,r.deviceId,r.type,r.manufacturer,r.model,r.serialNumber,r.holder,r.status,r.location,...(r.organisations||[])].some(v=>String(v||'').toLowerCase().includes(q)));},[data,query]);
 if(loading)return <main><div className="card">Loading Asset Manager reports…</div></main>;
 if(error)return <main><div className="card report-warning">{error}</div></main>;
 const s=data.summary||{}; const quality=rows.filter(r=>r.qualityIssues>0); const faults=[...rows].sort((a,b)=>b.faults-a.faults||b.openFaults-a.openFaults); const assignments=[...rows].sort((a,b)=>(a.holder||'').localeCompare(b.holder||'')||a.name.localeCompare(b.name)); const lifecycle=rows.filter(r=>r.warrantyState!=='Unknown').sort((a,b)=>String(a.warrantyExpiry).localeCompare(String(b.warrantyExpiry)));
 const exportData=()=>downloadCsv(`nuvriqo-asset-report-${new Date().toISOString().slice(0,10)}.csv`,['Device','Device ID','Type','Manufacturer','Model','Serial','Holder','Assignment Reference','Status','Location','Organisation','Purchase Date','Warranty Expiry','Warranty State','Primary Faults','Open Faults','Data Quality Issues'],rows.map(r=>[r.name,r.deviceId,r.type,r.manufacturer,r.model,r.serialNumber,r.holder,r.assignmentReference,r.status,r.location,(r.organisations||[]).join('; '),r.purchaseDate,r.warrantyExpiry,r.warrantyState,r.faults,r.openFaults,(r.missing||[]).join('; ')]));
 return <main className="reports-workspace"><div className="toolbar"><button className="secondary" onClick={onBack}>← Overview</button><button className="primary" onClick={exportData}>Export report CSV</button></div><div className="page-title"><span className="brand">NUVRIQO</span><h1>Asset Manager Reports</h1><p>Operational reporting across inventory, assignments, faults, organisations, lifecycle and data quality.</p></div>
 <div className="report-stats"><div><strong>{s.totalAssets||0}</strong><span>Total assets</span></div><div><strong>{s.openFaults||0}</strong><span>Open faults</span></div><div><strong>{s.unassigned||0}</strong><span>Unassigned</span></div><div><strong>{s.inRepair||0}</strong><span>In repair</span></div><div><strong>{(s.expiredWarranty||0)+(s.expiringWarranty||0)}</strong><span>Warranty attention</span></div><div><strong>{s.qualityIssues||0}</strong><span>Data quality</span></div></div>
 <div className="filters">{[['inventory','Inventory'],['faults','Faults'],['assignment','Assignment'],['organisation','Organisation'],['quality','Data quality'],['lifecycle','Lifecycle']].map(([k,l])=><button key={k} className={tab===k?'primary':'secondary'} onClick={()=>setTab(k)}>{l}</button>)}<input className="search" placeholder="Search report data…" value={query} onChange={e=>setQuery(e.target.value)}/></div>
 {tab==='inventory'&&<><div className="detail-grid"><GroupTable title="Assets by type" rows={data.byType}/><GroupTable title="Assets by status" rows={data.byStatus}/><GroupTable title="Assets by location" rows={data.byLocation}/></div><ReportTable title="Inventory" headers={['Device','Type','Status','Holder','Location','Serial']} rows={rows.map(r=>[r.name,r.type,r.status||'—',r.holder||'Unassigned',r.location||'—',r.serialNumber||'—'])}/></>}
 {tab==='faults'&&<ReportTable title="Fault history" subtitle="Devices with the highest number of primary Jira faults appear first." headers={['Device','Type','Primary faults','Open','Resolved','Last fault']} rows={faults.map(r=>[r.name,r.type,r.faults,r.openFaults,r.resolvedFaults,fmtDate(r.lastFault)])}/>} 
 {tab==='assignment'&&<><GroupTable title="Assets by holder" rows={data.byHolder}/><ReportTable title="Assignment report" headers={['Holder','Assignment reference','Device','Type','Status','Location']} rows={assignments.map(r=>[r.holder||'Unassigned',r.assignmentReference||'—',r.name,r.type,r.status||'—',r.location||'—'])}/></>}
 {tab==='organisation'&&<><GroupTable title="Assets by organisation" rows={data.byOrganisation}/><ReportTable title="Organisation report" subtitle="Organisation is derived from JSM requests linked through Device ID." headers={['Organisation','Device','Type','Holder','Open faults']} rows={rows.flatMap(r=>(r.organisations||[]).length?r.organisations.map(o=>[o,r.name,r.type,r.holder||'Unassigned',r.openFaults]):[['Unmapped',r.name,r.type,r.holder||'Unassigned',r.openFaults]])}/></>}
 {tab==='quality'&&<ReportTable title="Data quality report" subtitle="Incomplete asset records that need attention." headers={['Device','Missing information','Type','Holder','Location']} rows={quality.map(r=>[r.name,(r.missing||[]).join(', '),r.type,r.holder||'Unassigned',r.location||'—'])}/>} 
 {tab==='lifecycle'&&<ReportTable title="Lifecycle & warranty" headers={['Device','Purchase date','Warranty expiry','Warranty state','Status']} rows={lifecycle.map(r=>[r.name,fmtDate(r.purchaseDate),fmtDate(r.warrantyExpiry),r.warrantyState,r.status||'—'])}/>} 
 </main>;
}
function ReportTable({title,subtitle,headers,rows}){return <div className="card fault-card"><div className="section-head"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div><span>{rows.length} rows</span></div><div className="table-wrap"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{j===0?<strong>{v}</strong>:v}</td>)}</tr>)}</tbody></table></div></div>}
